<?php
$respuestas = array(
	"Me gustaría ser tu pijama para acostarme contigo.",
"Con esos coj*nes, si me quito los calzones.",
"Chupo, muerdo, masco, lamo.",
"Papacito te lo arrimo.",
"¿Cual es tu nombre? !Para pedirte a los Reyes Magos!.",
"Si necesitas afilar tu lápiz ya sabes donde está el sacapuntas.",
"Esos huevitos si están para estrellarlos.",
"Esa salchicha la quiere mi media noche.",
"Cuando veo tu hardware, se excita mi software.",
"Te invito a comer, yo soy el primer plato, el segundo y el postre.",
"Acabo de encontrar al padre de mis hijos.",
"Falta algo en mi cama y ese algo eres tú.",
"¿Te estudio o te trabajo?.",
"Si yo fuera un e-mail, tú serías mi contraseña.",
"Si así suena el chorro, ¿como sera la manguera?",
"Bonitos pantalones, quedarían muy bien en el suelo de mi dormitorio.",
"Con ese pajarito hasta yo canto.",
"Si vas a estar todo el día en mi mente al menos ponte ropa.",
"¿Te que crees policía? Qué me levantas cada vez que quieres.",
"Quien fuera mono para encaramarse en ese palo.",
"Quisiera ser hamburguesa y que me eches mucha mayonesa.",
"Con esa macana deberías ser policía.",
"Hey suegra présteme un estropajo para bañar a su hijo del ombligo para abajo.",
"¿Mi Rey jugamos a la basurita? Yo me tiro al piso y tu me recoges.",
"¿ Hijo de Apache? !!! APACHITO!!!",
"Si el veneno de las arañas entiesa a las ratas, qué veneno tendrás tu que me aguadas las patas.",
"Con esos brazos me gustaría ser conejo.",
"Metele el relleno a mi dona.",
"Para calentar mi bombón nada mas falta tu varita.",
"Quien fuera tu mano para poderte subir y bajar el zipper papacito.",
"Papito préstame a tu general que yo te lo hago mayor.",
"Amor, necesito llave para mi candado.",
"Apachurro, mojo y no me despeino.",
"¿Soy nueva aquí, me dices como llegar a tu casa.?",
"¿Compartimos el taxi a mi casa?",
"Papito, tu cosita se debería de llamar Bill Gates… por que es asquerosamente rico.",
"Quisiera que tu clavo ponche mis  llantas.",
"Podría sacarte de mi sucia lista de fantasías si quieres.",
"Jugamos al mecánico para que le metas mano a mi maquina.",
"Quisiera fueras aguacate para untarme en mis tortas.",
"Estoy loca por ti y quiero que seas mi loquero de cabecera.",
"En esa si me siento!",
"Si así esta el conejo como estará la zanahoria.",
"Quisiera que fueras el sol, para que me dieras todo el día.",
"Eres como un vino añejo, cada día te vuelves más sabroso y especial.",
"Debes estar cansado hoy, después de todo lo que hicimos en mi sueño anoche.",
"Estoy buscando el tocador de damas, ¿no eres tú?",
"Eres como el oso… Entre más peludo más hermoso.",
"Ojalá fuéramos elefantes, para caminar agarrándote la trompa con la cola.",
"Eres como una obra de arte, algo que no puedo dejar de admirar.",
"Como quisiera que estuvieras en mi frutero, mango podrido, por que ya te pasaste de bueno.",
"Adentro la verdura y arriba tu figura.",
"Papito te huele el ese a canela, a mi la cosita a vainilla, vamos a mi casa a hacer unas ricas natillas.",
"Que ganas de moverte la jaula para que salga el pajarito.",
"Chiquito no quiero ser enfadosa, pero que ganas de meter su dese en mi cosa.",
"Podrás hacer las cosas bien podrás hacer las cosas mal, yo lo único que quiero es que me abras el tamal.",
"Quisiera que te llamaras hambre para que me dieras a cada rato.",
"Chaparrito narizón, hazme lo que quieras pero quítame el calzón.",
"Hasta tu morada vengo a ver que determinas, si me atraviesas con los dedos o me das con el que orinas.",
"¡Chiquitito! Tú con toda esa herramienta y yo chambeando a mano.",
"Quien fuera director de orquesta para moverte la varita.",
"No me llamo Sabina ni Neruda, pero si te ando comiendo esa peluda.",
"No quiero la Luna ni que conquistes mi corazón, lo único que anhelo es tu cabezón.",
"Quien fuera pirata, no por el oro ni por la plata, sino por el tesoro que traes entre las patas.",
"Cuidado con las abejas joven, usted está hecho un caramelo.",
"Quisiera ser foca y tu cazador furtivo, para que me mates a palos.",
"Voy a estudiar brujería y hacerte un hechizo que me apodere pasa siempre de tu chorizo.",
"Hubieras estudiado para ginecólogo para que me metieras el DIU, el DIUsted.",
"Ay santo Niño de Atocha, que este hombre venga y me apuñale la pan%$.",
"En el cielo las estrellas, en las playas las gaviotas y en medio de mis piernas rebotando tus pelotas.",
"Bendita la cuchara del albañil que talló ese monumento, chiquitito.",
"Quisiera ser una dona para que me glasearas todita.",
"Con mi arroz y tu leche, vieras que buen atole haríamos.",
"¿Seguro que no eres un helado? Por qué se me antoja lamerte hasta el palo.",
"¿Vendes embutidos? ¿No? ¿Y ese salchichón?",
"Si lo que te cuelga fuera una nota musical lo dejaría RE-LA-MI-DO.",
"Ojalá fueras pared para revocarte completito, papacito.",
"Si fueras huérfano, yo te daría una mamá-a.",
"Quien fuera tu maestra de tercero para pasarte al cuarto, chiquitito.",
"Quisiera ser bolsa de súper para que metieras el pepino con todo y huevos.",
"Sana, sana, colita de rana. Si no me das hoy, ya me darás mañana.",
"Entre melón y melambes compraron una batería de cocina, melón cargó las sartenes y melambes la cazuela.",
"Quién fuera elástico de trusa para andarte dando unos rosones.",
"Me dicen LaLa por mi talento para sacar leche, ¿lo quieres comprobar?",
"En ese lavadero yo sí restregaba mis calzones, brasieres y hasta la pantufla.",
"Afuera la berenjena rey que me acabo de hacer vegana.",
"Ni fresa, ni zarzamora, es tu carita lo que enamora.",
"No sé mucho de futbol, pero si me metes las pelotas me doy por bien servida.",
"Si tu bigote fuera brocha y mi cosita un bizcocho, embadúrname cuanto quieras que yo no te reprocho.",
"¿Sabes la diferencia entre restar, dividir, sumar y multiplicar? Se resta la ropa, me divides las piernas y me sumas todo el producto.",
"¿Eres mecánico? Por que ando buscando quien me mida el aceite.",
"Al pan, pan. Al vino, vino. Y a mi papaya, tu pepino.",
"Ojalá fueras Superman para enamorarme de tu ese.",
"Lámeme tan fuerte que cuando tengamos un hijo salga peinadito de lado.",
"No soy Bimbo pero si te ando dando las medias nachas.",
"Quisiera que fueras tornillo y yo tuerca, para que me enrosques hasta que grite como puerca.",
"Si como lo mueves lo bates, ven y empújame el cacahuate.",
"¿Oye, trabajas en DHL? ¿No? ¿Y ese paquete?",
"Quien fuera verdulera para andar agarrando ese pepino.",
"Ojalá fueras bombero para apagar con tu manguera el incendio entre mis piernas.",
"Al cielo le falta un ángel, al bosque le falta un hada y a tu v3rg4 una buena mamada.",
"Quien fuera sartén para que estrellaras esos huevos.",
"Ojalá fueras Van Helsing y yo una vampira para que me atravesaras con tu estaca.",
"2×2=4×2=8 y para tu camote mi biscocho.",
"Ay mi vida estás pacheco… pa che cositas en la cama.",
"Eres como el chocolate, irresistible y adictivo. No puedo resistirme a tus encantos",
"Quisiera ser voladora de Papantla para colgarme de ese palo hasta que me dejes en el piso.",
"Yo soy toda una escultura y tú un escultor, ¿qué te parece si me pones en Pino Suarez?",
"Ya casi llega enero, ¿no se te antoja meterle el muñequito a la rosca?",
"Quien fuera tiro de pantalón para andar apretando ese paquetote.",
"Tienes todas las propiedades de un excelente café: bueno, fuerte y caliente.",
"Estás tan sabroso que te ha de saber a Takis Fuego.",
"Quisiera ser hamburguesa para que me la llenes de mayonesa.",
"Quien fuera paloma para zurrar ese poste.",
"Échamelos en los pechos, que aquí los termino de criar.",
"Bienaventurados los textiles que cubren ese hermoso paquete.",
"Quisiera ser Photoshop para tocarte y re-tocarte.",
"Papi… tírate un pedo y que carguen a mi cuenta todos los destrozos.",
"¿A dónde vas con ese marro? Aquí hay donde estrellarlo.",
"¿Te gusta la Arrolladora Banda el Limón? Porque te voy a tocar la cabecita dura.",
"Camote del bueno chorizo del fino, no más de verte yo sólita me empino.",
"Échamelos en la espalda para hacerles caballito.",
"Quisiera ser bruja y lanzarte un hechizo, para ser la dueña de tu chorizo.",
"¡Adiós corazón de melón, revolquémonos en mi cama, tú sin miedo y yo sin calzón!",
"Eres como el sol en un día frío, me calientas y me haces sentir viva.",
"Te quiero… pero luego te digo en que posición.",
"Quién fuera el agua de tu inodoro para reflejar lo que más añoro.",
"Chiquito precioso, échamelos en la oreja pa que me digan mamá.",
"Tú rostro ofende, pero ese paquete te defiende.",
"Quisiera ser elote para que me ensartes tu palote.",
"Entre broma y broma se asoma la cabezona.",
"Ayer pasé por tu casa y vi por la cerradura. Creí que era una planta, pero era tu cosa peluda.",
"Eres como una canción de amor que nunca me canso de escuchar.",
"Poncho, plancho, aplasto y lavo a domicilio.",
"Las flores se adelantaron y salieron en febrero, tú pon la reata y yo pongo el florero.",
"Échamelos en la oreja para escuchar cuando me digan mamá.",
"Amor, échamelos en la espalada para hacerles caballito.",
"Te bajaría una estrella, pero me quemaría como ocote, mejor te bajo la bragueta y te chupo el camote.",
"Quien fuera elástico para andarte rozando en la trusa. ",
"Eres un perfecto amor… amortiguador para mis caderas. ",
"Con ese chorizo échame dos con todo, pero sin cebolla que luego me apesta el hocico. ",
"Mi amor, quien fuera papel higiénico para andar tallando esas nalgas. ",
"Quisiera darle unas lamidas a tu novia para saber a qué sabes. ",
"¿Disculpa, vendes dulces? Por que ya se me antojó chuparte la paleta. ",
"¡Ay que belleza, hasta me escurrieron las lágrimas de abajo! ",
"Estás tan bueno que, aunque sean las doce del día, llevo una lampara para cogerte con la luz prendida. ",
"¿Ya tramitaste tu licencia de conducir? Porque es ilegal manejar tanta sabrosura. ",
"Yo te la lambo hasta que se te aclare. ",
"Soñé que era chofer y te manejaba a mi antojo. ",
"Si así como caminas, cocinas, me comería todo ese birote."
);
$random=array_rand($respuestas);
$piropo=$respuestas[$random];
?>
